Repository teamneusta/converter-bundle, pull requests merged in 2023-01, with the labels that each got.

#10 Refactor/use decorator pattern
  config/services.yaml
  src/Converter/DefaultCachedConverter.php
  tests/Converter/DefaultCachedConverterTest.php
  tests/app/config/services.yaml
Labels: BC-BREAK

#17 Fix cached converter
  config/services.yaml
  src/Converter/DefaultCachedConverter.php
  tests/app/config/services.yaml
Labels: bug

#11 Prefix services
  config/services.yaml
  docs/cached-converter.md
  docs/usage.md
  tests/app/config/services.yaml
Labels: BC-BREAK

#12 Allow any object as context
  docs/usage.md
  src/Converter/CachedConverter.php
  src/Converter/Converter.php
  src/Converter/ConverterContext.php
  src/Converter/DefaultCachedConverter.php
  src/Converter/DefaultConverter.php
  src/Converter/DefaultConverterContext.php
  src/Factory/TargetTypeFactory.php
  src/Populator/Populator.php
  tests/Converter/DefaultCachedConverterIntegrationTest.php
  tests/Converter/DefaultCachedConverterTest.php
  tests/Converter/DefaultConverterIntegrationTest.php
  tests/Converter/DefaultConverterTest.php
  tests/Fixtures/Factory/PersonFactory.php
  tests/Fixtures/Populator/PersonNamePopulator.php
Labels: enhancement, BC-BREAK

#20 Get rid of unnecessary `CachedConverter` interface
  docs/cached-converter.md
  src/Converter/CachedConverter.php
  src/Converter/DefaultCachedConverter.php
  tests/Converter/CachedConverterIntegrationTest.php
  tests/Converter/CachedConverterTest.php
  tests/app/config/services.yaml
Labels: BC-BREAK

#21 Allow defining converters via Symfony configuration
  docs/cached-converter.md
  docs/usage.md
  phpstan.neon
  phpunit.xml.dist
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/NeustaConverterExtension.php
  tests/DependencyInjection/NeustaConverterExtensionTest.php
  tests/app/TestKernel.php
  tests/app/bin/console
  tests/app/config/packages/framework.yaml
  tests/app/config/packages/neusta_converter.yaml
  tests/app/config/services.yaml
Labels: enhancement
